//! Tests for the credential both ingestion paths carry.
//!
//! Worth more than most of this crate's tests, because none of them depends on
//! what a provider sends: a header either goes out or it does not, and a
//! `{:?}` either prints a secret or it does not.

use super::*;

/// The token every test looks for afterwards. Distinctive on purpose: a
/// substring search for it must not match anything a redaction leaves behind.
const TOKEN: &str = "s3cret-token-value";

const URL: &str = "wss://example.invalid/stream";

fn credential(name: &str) -> Credential {
    Credential::new(Some((name, SecretKey::for_tests(TOKEN)))).expect("a valid name and value")
}

fn url() -> SecretUrl {
    SecretUrl::for_tests(URL)
}

// ── the header reaches the WebSocket handshake ──────────────────────

/// ⚠️ **The point of this whole module, and the answer to a review objection:**
/// what decides whether there is a header is the operator's configuration, not
/// the transport. Until 10 September 2026 `INGEST_SOURCE` decided, on the
/// belief that the WebSocket client could not carry one — it can, and this is
/// the test that says so.
#[test]
fn the_websocket_handshake_carries_the_configured_header() {
    let request = credential("x-token")
        .ws_request(&url())
        .expect("the url is a valid websocket endpoint");

    assert_eq!(
        request
            .headers()
            .get("x-token")
            .map(|v| v.to_str().expect("ascii")),
        Some(TOKEN),
        "the credential must reach the wire on this path too"
    );
}

/// And the handshake stays a handshake: adding a header must not cost the
/// fields `tungstenite` refuses a request without.
#[test]
fn the_handshake_keeps_the_fields_the_protocol_requires() {
    let request = credential("x-token").ws_request(&url()).expect("valid");

    for required in [
        "host",
        "connection",
        "upgrade",
        "sec-websocket-version",
        "sec-websocket-key",
    ] {
        assert!(
            request.headers().contains_key(required),
            "`{required}` is generated by `into_client_request`, and a request \
             missing it is refused before it is sent"
        );
    }
    assert_eq!(request.uri().to_string(), URL);
}

/// An endpoint with no header is a first-class case: a self-hosted Yellowstone
/// takes no credential, and a provider may want it inside the URL.
#[test]
fn an_endpoint_without_a_header_adds_none() {
    let credential = Credential::new(None).expect("no header is valid");

    let request = credential.ws_request(&url()).expect("valid");

    assert!(request.headers().get("x-token").is_none());
    assert_eq!(credential.name(), None);
}

/// The name is the operator's, not ours — `authorization: Bearer {key}` is as
/// legitimate a shape as `x-token`, and the code knows neither provider.
#[test]
fn any_header_name_the_operator_writes_is_used() {
    let request = credential("authorization")
        .ws_request(&url())
        .expect("valid");

    assert!(request.headers().contains_key("authorization"));
    assert!(
        !request.headers().contains_key("x-token"),
        "nothing here favours one provider's convention"
    );
}

// ── the token is printed by nothing ─────────────────────────────────

/// ⚠️ **The acceptance criterion of the ticket, in the one form a test can
/// carry it.**
///
/// ⚠️ What turns it red is **both** guards going: measured by mutation on
/// 9 September 2026, replacing the hand-written `Debug` by a derive keeps it
/// green on its own, because `set_sensitive` makes `HeaderValue`'s own `Debug`
/// print `Sensitive`. Written down because the natural reading — "it pins the
/// manual impl" — is wrong, and a test believed to guard something it does not
/// is worse than no test.
#[test]
fn debug_never_prints_the_token() {
    let printed = format!("{:?}", credential("x-token"));

    assert!(
        !printed.contains(TOKEN),
        "the token must not survive a `{{:?}}`, and it did: {printed}"
    );
    assert!(
        printed.contains("x-token"),
        "the header *name* must stay legible — it is the diagnostic that tells \
         an operator their provider expects a different one"
    );
}

/// The guard that covers code this repository does not write: the layers that
/// dump request headers honour the sensitive flag.
#[test]
fn the_header_value_is_marked_sensitive() {
    let credential = credential("x-token");
    let (_, value) = credential.header().expect("a header is set");

    assert!(
        value.is_sensitive(),
        "an unmarked value is one a third-party header dump prints in full"
    );
}

/// ⚠️ And a request built from it keeps the flag — the property only pays off
/// where the value actually travels.
#[test]
fn the_flag_survives_into_the_handshake_request() {
    let request = credential("x-token").ws_request(&url()).expect("valid");

    assert!(
        request
            .headers()
            .get("x-token")
            .expect("set")
            .is_sensitive()
    );
}

// ── refusals name the line to fix, never the secret ─────────────────

/// A malformed name is a startup failure, not a per-attempt one: the
/// configuration will not fix itself between two connections.
#[test]
fn a_header_name_that_is_not_a_token_is_refused_at_construction() {
    let error = Credential::new(Some(("x token", SecretKey::for_tests(TOKEN))))
        .expect_err("a space is not allowed in a header name");

    assert!(
        matches!(error, CredentialError::InvalidHeaderName { .. }),
        "got {error:?}"
    );
    assert!(
        !error.to_string().contains(TOKEN),
        "a refusal about the name has no business quoting the value"
    );
}

/// ⚠️ And the refusal about the **value** must not quote the value either —
/// which is the one an error message would most naturally do, since that is
/// what is wrong with it.
#[test]
fn a_refused_header_value_is_never_quoted_back() {
    // A newline cannot appear in a header value; it is also what a credential
    // pasted with its line ending looks like.
    let broken = format!("{TOKEN}\n");
    let error = Credential::new(Some(("x-token", SecretKey::for_tests(&broken))))
        .expect_err("a newline is not allowed in a header value");

    assert!(
        matches!(error, CredentialError::InvalidHeaderValue { .. }),
        "got {error:?}"
    );
    let printed = format!("{error} {error:?}");
    assert!(
        !printed.contains(TOKEN),
        "neither Display nor Debug may carry the credential: {printed}"
    );
    assert!(
        printed.contains("x-token"),
        "the header name is what the operator needs to find the line"
    );
}

/// A URL that is not a WebSocket endpoint fails **before** any connection, and
/// its message is scrubbed: the error quotes the URL, which carries the key
/// whenever the operator put it there rather than in a header.
#[test]
fn a_url_that_is_not_a_websocket_endpoint_is_refused_scrubbed() {
    let url = SecretUrl::for_tests("wss://example.invalid/?api-key=s3cret-in-the-url");
    let credential = Credential::new(None).expect("no header");

    // ⚠️ Not a wrong *scheme*: `into_client_request` accepts `ftp://` and lets
    // the connection refuse it later, which this test asserted until it was
    // run. What it does refuse is a string that is not a URI at all.
    let broken = SecretUrl::for_tests("not a uri at all");
    assert!(credential.ws_request(&broken).is_err());

    // And the sound one still carries its query untouched — the request is what
    // the operator wrote, key included, since that is where they put it.
    let request = credential.ws_request(&url).expect("valid");
    assert!(request.uri().to_string().contains("api-key="));
}
